INSERT INTO category (name) VALUES ('American');
INSERT INTO category (name) VALUES ('Italian');
INSERT INTO category (name) VALUES ('Mexican');
INSERT INTO category (name) VALUES ('Fast Food');
INSERT INTO measurement_unit (unit_name) VALUES ('Teaspoon');
INSERT INTO measurement_unit (unit_name) VALUES ('Tablespoon');
INSERT INTO measurement_unit (unit_name) VALUES ('Cup');
INSERT INTO measurement_unit (unit_name) VALUES ('Pinch');
INSERT INTO measurement_unit (unit_name) VALUES ('Pint');
INSERT INTO measurement_unit (unit_name) VALUES ('Ounce');
INSERT INTO measurement_unit (unit_name) VALUES ('Pcs');
INSERT INTO measurement_unit (unit_name) VALUES ('Dash');